// AUTOGENERATED - DO NOT MODIFY
import DashboardView from '../src/views/DashboardView';import PaymentDetailView from '../src/views/PaymentDetailView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-01-11 07:26:14.161309195 +0000 UTC m=+0.818061474';

export { 
  DashboardView,	

  PaymentDetailView	
 };

export default {
  "app_backend": {
    "webhooks": null
  },
  "connect_permissions": null,
  "distribution_type": "private",
  "icon": "./icon.png",
  "id": "com.swa.surcharge",
  "name": "SWA - Surcharge Automation",
  "permissions": [
    {
      "permission": "customer_read",
      "purpose": "Read customer billing address for state compliance checks when determining surcharge eligibility"
    },
    {
      "permission": "payment_method_read",
      "purpose": "Detect card funding type (credit vs debit) to apply surcharges only to eligible credit card transactions"
    },
    {
      "permission": "payment_intent_write",
      "purpose": "Update payment amount to include calculated surcharge and store tracking metadata"
    }
  ],
  "ui_extension": {
    "views": [
      {
        "component": "DashboardView",
        "viewport": "stripe.dashboard.home.overview"
      },
      {
        "component": "PaymentDetailView",
        "viewport": "stripe.dashboard.payment.detail"
      }
    ]
  },
  "version": "0.1.3"
};
